Development
21stCheran/ItemsLogger pull request #5
Opened 2021-01-22 06:02 UTC by 21stCheran

2021-01-22 18:17 UTC, Blue0ni requested changes

2021-01-22 18:17 UTC, Blue0ni commented on .gitignore
> +# Ignore Gradle GUI config
```suggestion
# Eclipse
.settings/

# Ignore Gradle GUI config
```

do `git rm .settings/` as well

2021-01-22 18:17 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/ItemPlayer.java
Bruh, move `savePlayer` and `loadInventory` to another class. Literally the 3rd time I've told you to do this.

2021-01-22 18:17 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/ItemsLogger.java
> +		this.getCommand("openitemlog").setExecutor(new OpenItemLog());
Strings

2021-01-22 18:17 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/commands/MainCommand.java
> +}
One class per file excepting inner classes

2021-01-22 18:17 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/commands/ReloadConfig.java
> +		sender.sendMessage("§8[§cItemsLogger§8] §eyou do not have access to this command.");
[Bukkit has built in colour codes](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html#translateAlternateColorCodes(char,%20java.lang.String))

2021-01-22 18:17 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/commands/SearchLogs.java
> +			sender.sendMessage("§8[§cItemsLogger§8] §eyou do not have access to this command.");
See previous comment

2021-01-22 18:17 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/utils/Storage.java
> +			args.add(max);
First argument of `LIMIT` is how many rows to skip. Second arg is how many rows to take
```suggestion
			sb.append(" LIMIT ?, ?");
			args.add(min);
			args.add(max - min);
```

2021-01-22 21:06 UTC, stein-ein requested changes

2021-01-22 21:06 UTC, stein-ein commented on src/main/java/com/twentyonec/ItemsLogger/commands/OpenItemLog.java
> +			sender.sendMessage(ChatHandler.PREFIX + ChatColor.YELLOW
As a rule of thumb, avoid magic values. Any strings/numbers/whatever that are hardcoded directly into some function without any labeling/explanation (like variable name) are called magic values. They should almost always be replaced with a constant/enum which would then be referenced wherever appropriate. This does three things:

1. Makes the purpose of the value very clear. It's obvious what value `NO_PERMISSION_MESSAGE` holds.
2. Reduces repetition. Instead of hardcoding the same value (like no permission error) in multiple locations, you just do it once.
3. Makes modification easy. Whenever you want to change the message, you just change it that one place and you're done.

I suggest you create an enum `Messages` in which you could define all messages and have some helper methods like `formatMessage` etc... That's generally how you handle messages in any plugin/program.

2021-01-22 21:55 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/commands/OpenItemLog.java
> +																		+ " Inventory");
```suggestion
				String inventoryName = itemPlayer.getCause() + " Inventory";
				final Inventory inv = Bukkit.createInventory(null, 54, inventoryName);
```

2021-01-22 21:55 UTC, Blue0ni commented on src/main/java/com/twentyonec/ItemsLogger/listeners/DeathSave.java
> +					storage.saveItemPlayer(itemPlayer);
Always use `this` for class variables
```suggestion
					this.storage.saveItemPlayer(itemPlayer);
```

2021-01-23 15:21 UTC, Blue0ni approved these changes

2021-01-23 15:21 UTC, Blue0ni commented
Wait for Stein's approval

2021-01-23 15:31 UTC, stein-ein approved these changes

2021-01-23 15:43 UTC, merged